apiVersion: v1
data:
  myvalue: Hello World
  food: {{  .Values.favourite.food | upper | quote  }}
  drink: {{  .Values.favourite.drink | default "tea" | upper }}
  {{ if eq .Values.favourite.drink "coffee"  }}
  mug: true
  {{ end }}
  
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{  .Release.Name  }}-configmap
